// Code generated by go-swagger; DO NOT EDIT.

package collection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"Vectory/pkg/models"
)

// AddCollectionReader is a Reader for the AddCollection structure.
type AddCollectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddCollectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAddCollectionCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddCollectionCreated creates a AddCollectionCreated with default headers values
func NewAddCollectionCreated() *AddCollectionCreated {
	return &AddCollectionCreated{}
}

/*AddCollectionCreated handles this case with default header values.

Created successfully
*/
type AddCollectionCreated struct {
	Payload *models.CollectionCreated
}

func (o *AddCollectionCreated) Error() string {
	return fmt.Sprintf("[POST /v1/collection][%d] addCollectionCreated  %+v", 201, o.Payload)
}

func (o *AddCollectionCreated) GetPayload() *models.CollectionCreated {
	return o.Payload
}

func (o *AddCollectionCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CollectionCreated)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
