// Code generated by go-swagger; DO NOT EDIT.

package collection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"Vectory/pkg/models"
)

// DeleteCollectionReader is a Reader for the DeleteCollection structure.
type DeleteCollectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCollectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteCollectionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteCollectionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteCollectionOK creates a DeleteCollectionOK with default headers values
func NewDeleteCollectionOK() *DeleteCollectionOK {
	return &DeleteCollectionOK{}
}

/*DeleteCollectionOK handles this case with default header values.

valid operation
*/
type DeleteCollectionOK struct {
	Payload *models.APIResponse
}

func (o *DeleteCollectionOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/collection/{collectionName}][%d] deleteCollectionOK  %+v", 200, o.Payload)
}

func (o *DeleteCollectionOK) GetPayload() *models.APIResponse {
	return o.Payload
}

func (o *DeleteCollectionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteCollectionBadRequest creates a DeleteCollectionBadRequest with default headers values
func NewDeleteCollectionBadRequest() *DeleteCollectionBadRequest {
	return &DeleteCollectionBadRequest{}
}

/*DeleteCollectionBadRequest handles this case with default header values.

Invalid collection name
*/
type DeleteCollectionBadRequest struct {
}

func (o *DeleteCollectionBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /v1/collection/{collectionName}][%d] deleteCollectionBadRequest ", 400)
}

func (o *DeleteCollectionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
