// Code generated by go-swagger; DO NOT EDIT.

package collection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCollectionParams creates a new GetCollectionParams object
// with the default values initialized.
func NewGetCollectionParams() *GetCollectionParams {
	var ()
	return &GetCollectionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCollectionParamsWithTimeout creates a new GetCollectionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCollectionParamsWithTimeout(timeout time.Duration) *GetCollectionParams {
	var ()
	return &GetCollectionParams{

		timeout: timeout,
	}
}

// NewGetCollectionParamsWithContext creates a new GetCollectionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCollectionParamsWithContext(ctx context.Context) *GetCollectionParams {
	var ()
	return &GetCollectionParams{

		Context: ctx,
	}
}

// NewGetCollectionParamsWithHTTPClient creates a new GetCollectionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCollectionParamsWithHTTPClient(client *http.Client) *GetCollectionParams {
	var ()
	return &GetCollectionParams{
		HTTPClient: client,
	}
}

/*GetCollectionParams contains all the parameters to send to the API endpoint
for the get collection operation typically these are written to a http.Request
*/
type GetCollectionParams struct {

	/*CollectionName
	  Collection name to delete

	*/
	CollectionName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get collection params
func (o *GetCollectionParams) WithTimeout(timeout time.Duration) *GetCollectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get collection params
func (o *GetCollectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get collection params
func (o *GetCollectionParams) WithContext(ctx context.Context) *GetCollectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get collection params
func (o *GetCollectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get collection params
func (o *GetCollectionParams) WithHTTPClient(client *http.Client) *GetCollectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get collection params
func (o *GetCollectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCollectionName adds the collectionName to the get collection params
func (o *GetCollectionParams) WithCollectionName(collectionName string) *GetCollectionParams {
	o.SetCollectionName(collectionName)
	return o
}

// SetCollectionName adds the collectionName to the get collection params
func (o *GetCollectionParams) SetCollectionName(collectionName string) {
	o.CollectionName = collectionName
}

// WriteToRequest writes these params to a swagger request
func (o *GetCollectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param collectionName
	if err := r.SetPathParam("collectionName", o.CollectionName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
